export const languageOptions = [
  { label: 'Tiếng Ả Rập', value: 'ar' },
  { label: 'Tiếng Anh', value: 'en' },
  { label: 'Tiếng Ba Lan', value: 'pl' },
  { label: 'Tiếng Bengali', value: 'bn' },
  { label: 'Tiếng Bồ Đào Nha', value: 'pt' },
  { label: 'Tiếng Bồ Điệp', value: 'my' },
  { label: 'Tiếng Đức', value: 'de' },
  { label: 'Tiếng Filipino', value: 'tl' },
  { label: 'Tiếng Hà Lan', value: 'nl' },
  { label: 'Tiếng Hausa', value: 'ha' },
  { label: 'Tiếng Hindi', value: 'hi' },
  { label: 'Tiếng Hy Lạp', value: 'el' },
  { label: 'Tiếng Indonesia', value: 'id' },
  { label: 'Tiếng Italia', value: 'it' },
  { label: 'Tiếng Nhật', value: 'ja' },
  { label: 'Tiếng Hàn', value: 'ko' },
  { label: 'Tiếng Malay', value: 'ms' },
  { label: 'Tiếng Nga', value: 'ru' },
  { label: 'Tiếng Pháp', value: 'fr' },
  { label: 'Tiếng Phạn', value: 'fa' },
  { label: 'Tiếng Roman', value: 'ro' },
  { label: 'Tiếng Swahili', value: 'sw' },
  { label: 'Tiếng Tây Ban Nha', value: 'es' },
  { label: 'Tiếng Thái', value: 'th' },
  { label: 'Tiếng Thổ Nhĩ Kỳ', value: 'tr' },
  { label: 'Tiếng Tamil', value: 'ta' },
  { label: 'Tiếng Trung', value: 'zh' },
  { label: 'Tiếng Ukraina', value: 'uk' },
  { label: 'Tiếng Urdu', value: 'ur' },
  { label: 'Tiếng Việt', value: 'vi' },
]
