name: Deploy Quasar to AWS EC2 with Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Quasar CLI
        run: npm install -g @quasar/cli

      - name: Build Quasar app
        run: quasar build

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > private_key
          chmod 600 private_key
          rsync -avz --delete -e "ssh -i private_key -o StrictHostKeyChecking=no" dist/spa/ $EC2_USER@$EC2_HOST:/usr/share/nginx/html/my-quasar-app/
          rm private_key
